
package br.com.trapp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.5
 * Mon Nov 07 14:55:31 BRST 2016
 * Generated source version: 3.1.5
 */

@XmlRootElement(name = "consultaResponse", namespace = "http://trapp.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultaResponse", namespace = "http://trapp.com.br/")

public class ConsultaResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

