
package br.com.trapp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.5
 * Mon Nov 07 14:55:31 BRST 2016
 * Generated source version: 3.1.5
 */

@XmlRootElement(name = "consulta", namespace = "http://trapp.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consulta", namespace = "http://trapp.com.br/")

public class Consulta {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

