
package br.com.trapp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.5
 * Mon Nov 07 14:52:26 BRST 2016
 * Generated source version: 3.1.5
 */

@XmlRootElement(name = "registra", namespace = "http://trapp.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registra", namespace = "http://trapp.com.br/")

public class Registra {


}

